apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-argo-app
  namespace: argocd
spec:
  project: default
 
  source:
    repoURL: https://github.com/LevAriC/wordpress-app-argocd.git
    targetRevision: HEAD
    path: definitions
 
  destination: 
    server: https://kubernetes.default.svc
    namespace: wordpress-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true