apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 5000
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: wordpress
    tier: frontend